title:        Bloody Marie
description:  Blog about menstrual cycle tracking
theme:        jekyll-theme-cayman

tagline:      It's about your menstrual health, baby!
baseurl:      ""
# paginate:     1

# About/contact
author:
  name:       lilaluca
  url:        https://github.com/lilaluca

# Gems
gems:
              - jekyll-paginate

#Others
markdown:     kramdown
